name: mangaku
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  salomon_bottom_bar: ^3.3.2
  persistent_bottom_nav_bar: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.2
  freezed_annotation: ^2.4.4
  flutter_bloc: ^9.1.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  http: ^1.3.0
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: 3.3.1
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.13

  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
